# cloudbuild.yaml para PersonalFinance.Api.Backend (Versión Consistente con europe-west1)
steps:
# 1. Construir la imagen de Docker
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '-t'
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/personal-finances-13/backend:$COMMIT_SHA' # <-- CAMBIO A europe-west1
  - '.'
# 2. Subir la imagen a Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'push'
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/personal-finances-13/backend:$COMMIT_SHA' # <-- CAMBIO A europe-west1

# 3. Desplegar en Cloud Run (Formato de Variables Corregido + Región Consistente)
- name: 'gcr.io/cloud-builders/gcloud'
  timeout: '600s' 
  args:
  - 'run'
  - 'deploy'
  - 'personalfinance-api-backend'
  - '--image'
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/personal-finances-13/backend:$COMMIT_SHA'
  - '--region'
  - 'europe-west1' # <-- CAMBIO A europe-west1
  - '--port'
  - '8080'
  - '--set-env-vars'
  - >-
    ASPNETCORE_ENVIRONMENT=$_ASPNETCORE_ENVIRONMENT,
    ConnectionStrings__DefaultConnection=$_CONNECTION_STRING,
    Cors__AllowedOrigins__0=$_CORS_ALLOWED,
    Jwt__Audience=$_JWT_AUDIENCE,
    Jwt__ExpireMinutes=$_JWT_EXPIREMINUTES,
    Jwt__Issuer=$_JWT_ISSUER,
    Jwt__Key=$_JWT_KEY,
    SendGrid__ApiKey=$_SENDGRID_APIKEY,
    SendGrid__FromEmail=$_SENDGRID_FROMEMAIL,
    SendGrid__FromName=$_SENDGRID_FROMNAME,
    SendGrid__SandboxMode=$_SENDGRID_SANDBOXMODE
  
  - '--allow-unauthenticated'
options:
  logging: CLOUD_LOGGING_ONLY