namespace PersonalFinance.Api.Features.Ledger.Common
{
    public sealed record ConceptMappingTemplate(
        string Pattern,
        string ConceptName,
        string? AccountName,
        int Priority);

    /// <summary>
    /// Reglas verificadas contra los extractos Revolut de las cuentas personal
    /// y conjunta. Los patrones ya están en la forma producida por
    /// <see cref="RevolutMovementClassifier.Normalize"/>.
    /// </summary>
    public static class ConceptMappingTemplates
    {
        public static IReadOnlyList<ConceptMappingTemplate> Rules { get; } =
            new List<ConceptMappingTemplate>
            {
                new(
                    "JENNY MABEL ESPINOZA SEJAS & MARCEL ORLANDO UGARTE ESPINOZA",
                    "Movimiento entre mis bancos",
                    null,
                    200),
                new(
                    "MARCEL ORLANDO UGARTE ESPINOZA",
                    "Movimiento entre mis bancos",
                    null,
                    200),
                new("POCKET", "Hucha y fondos Revolut", null, 100),
                new("FLEXIBLE CASH FUNDS", "Hucha y fondos Revolut", null, 100),
                new(
                    "UNA RECARGA DE APPLE PAY CON",
                    "Recarga desde mis tarjetas",
                    null,
                    100),
                new(
                    "TO MARCEL UGARTE ESPINOZA",
                    "Movimiento entre mis bancos",
                    "Personal",
                    100),
                new("PAGO DE WOLTERS KLUWER", "Nómina", "Personal", 100),
                new(
                    "TRANSFERENCIA DE JENNY MABEL ESPINOZA SEJAS",
                    "Préstamos cobrados",
                    "Personal",
                    90),
                new(
                    "TRANSFERENCIA A JENNY MABEL ESPINOZA SEJAS",
                    "Préstamos entregados",
                    "Personal",
                    90),
                new(
                    "TRANSFERENCIA DE VANESSA ISABEL MARQUEZ DE CABALLERO",
                    "Liquidaciones familiares",
                    "Personal",
                    100),
                new(
                    "TO VANESSA ISABEL MARQUEZ DE CABALLERO",
                    "Transferencias y Bizum enviados",
                    "Personal",
                    100),
                new(
                    "TRANSFERENCIA DE JENNY MABEL ESPINOZA SEJAS",
                    "Aportaciones familiares",
                    "Conjunta",
                    90),
                new("MERCADONA", "Supermercado y alimentación del hogar", null, 80),
                new("LIDL", "Supermercado y alimentación del hogar", null, 80),
                new("ULFAT FRUTAS I VERDURAS", "Supermercado y alimentación del hogar", null, 80),
                new("FRUITES I VERDURES", "Supermercado y alimentación del hogar", null, 80),
                new("MCDONALD'S", "Restaurantes y cafeterías", null, 80),
                new("HECTAREA INMOBILIARIA", "Alquiler", "Conjunta", 80),
                new("HECTAREA SERVICIOS INMOBILIARIOS", "Alquiler", "Conjunta", 90),
                new("SECURITAS DIRECT", "Seguridad del hogar", "Conjunta", 80),
                new("O2 FIBRA", "Internet y telefonía", "Conjunta", 80),
                new("O2", "Internet y telefonía", "Conjunta", 70),
                new("ENI PLENITUDE", "Gas", "Conjunta", 80),
                new("PLENITUDE", "Gas", "Conjunta", 70),
                new("AIGUES DE BARCELONA", "Agua", "Conjunta", 80),
                new("COMERCIALIZADORA", "Electricidad", "Conjunta", 80),
                new("ASISTENCIA SANITARIA", "Seguro médico", "Conjunta", 80),
                new("ASSISTENCIA SANITARIA", "Seguro médico", "Conjunta", 80),
                new("CAJA DE SEGUROS REUNIDOS", "Seguro del hogar", "Conjunta", 80),
                new("FREENOW", "Transporte diario", null, 80),
                new("TRAINLINE", "Viajes y alojamiento", null, 80),
                new("NETFLIX", "Netflix", null, 80),
                new("AMAZON PRIME", "Amazon Prime", null, 90),
                new("APPLE", "Apple", null, 80),
                new("SPLIIIT", "Spliiit", null, 80),
                new("GOOGLE ONE", "Software y servicios digitales", null, 80),
                new("RAILWAY", "Software y servicios digitales", null, 80),
                new("CHATGPT", "Software y servicios digitales", null, 80),
                new("CANVA", "Software y servicios digitales", null, 80),
                new("SPOTIFY", "Spotify", null, 80),
                new("CRUNCHYROLL", "Ocio y entretenimiento", null, 80),
                new("DEEVID AI", "Software y servicios digitales", null, 80),
                new("AMAZON", "Compras personales", null, 70),
                new("CONDIS", "Supermercado y alimentación del hogar", null, 80),
                new("DIA", "Supermercado y alimentación del hogar", null, 80),
                new("ALDI", "Supermercado y alimentación del hogar", null, 80),
                new("CONSUM", "Supermercado y alimentación del hogar", null, 80),
                new("COVIRAN", "Supermercado y alimentación del hogar", null, 80),
                new("EDEKA", "Supermercado y alimentación del hogar", null, 80),
                new("TESCO", "Supermercado y alimentación del hogar", null, 80),
                new("NAVAS ALIMENTACION", "Supermercado y alimentación del hogar", null, 80),
                new("SUPERMERCADO PRIVILEGIOS", "Supermercado y alimentación del hogar", null, 80),
                new("UBER EATS", "Restaurantes y cafeterías", null, 80),
                new("JUST EAT", "Restaurantes y cafeterías", null, 80),
                new("GLOVO", "Restaurantes y cafeterías", null, 80),
                new("KFC", "Restaurantes y cafeterías", null, 80),
                new("BURGER KING", "Restaurantes y cafeterías", null, 80),
                new("STARBUCKS", "Restaurantes y cafeterías", null, 80),
                new("GOIKO", "Restaurantes y cafeterías", null, 80),
                new("Kebab", "Restaurantes y cafeterías", null, 70),
                new("RESTAURANTE", "Restaurantes y cafeterías", null, 70),
                new("CAFE", "Restaurantes y cafeterías", null, 60),
                new("BAR ", "Restaurantes y cafeterías", null, 50),
                new("UBER", "Transporte diario", null, 80),
                new("BOLT", "Transporte diario", null, 80),
                new("TAXI", "Transporte diario", null, 80),
                new("TRANSPORTS METROPOLITANS", "Transporte diario", null, 80),
                new("METRO DE MADRID", "Transporte diario", null, 80),
                new("MONBUS", "Transporte diario", null, 80),
                new("RYANAIR", "Viajes y alojamiento", null, 80),
                new("VUELING", "Viajes y alojamiento", null, 80),
                new("FLIXBUS", "Viajes y alojamiento", null, 80),
                new("BOOKING.COM", "Viajes y alojamiento", null, 80),
                new("HOSTELWORLD", "Viajes y alojamiento", null, 80),
                new("HOSTEL", "Viajes y alojamiento", null, 70),
                new("GENERATOR", "Viajes y alojamiento", null, 70),
                new("ESIM", "Internet y telefonía", null, 80),
                new("VODAFONE", "Internet y telefonía", null, 80),
                new("1GLOBAL", "Internet y telefonía", null, 80),
                new("PRIMARK", "Ropa y calzado", null, 80),
                new("NIKE", "Ropa y calzado", null, 80),
                new("ZARA", "Ropa y calzado", null, 80),
                new("DUNNES STORES", "Ropa y calzado", null, 70),
                new("BARBER", "Belleza y peluquería", null, 80),
                new("SALON DE BELLEZA", "Belleza y peluquería", null, 80),
                new("MCB ARIBAU", "Belleza y peluquería", null, 80),
                new("CENTRE VETERINARI", "Mascotas (Zoey y Zeus)", null, 80),
                new("ROVER", "Mascotas (Zoey y Zeus)", null, 80),
                new("JUANA DOG", "Mascotas (Zoey y Zeus)", null, 80),
                new("UDEMY", "Formación", null, 80),
                new("CINESA", "Ocio y entretenimiento", null, 80),
                new("CINE YELMO", "Ocio y entretenimiento", null, 80),
                new("TICKETMASTER", "Ocio y entretenimiento", null, 80),
                new("MUSEO", "Ocio y entretenimiento", null, 70),
                new("ESCAPEUP", "Ocio y entretenimiento", null, 80),
                new("KLARNA", "Servicios legales y gestión de deudas", null, 80),
                new("RIVERTY", "Servicios legales y gestión de deudas", null, 80),
                new("DEUDAFIX", "Servicios legales y gestión de deudas", null, 80),
                new("JUZGADO", "Servicios legales y gestión de deudas", null, 80),
                new("AGENCIA TRIBUTARIA", "Impuestos y tasas", null, 80),
                new("DEVOLUCIONES TRIBUTARIAS", "Reembolsos y devoluciones", null, 90),
                new("RETIRADA DE EFECTIVO", "Retiradas de efectivo", null, 80),
                new("BIZUM PAYMENT TO", "Transferencias y Bizum enviados", null, 70),
                new("TRANSFERENCIA A", "Transferencias y Bizum enviados", null, 40),
                new("TRANSFERENCIA DE", "Ingresos adicionales", null, 40),
                new("DINERO ANADIDO A TRAVES DE BIZUM", "Ingresos adicionales", null, 70)
            };
    }
}
