using System.Threading;
using System.Threading.Tasks;
using PersonalFinance.Api.Models.Entities;

namespace PersonalFinance.Api.Services.Contracts
{
    public interface IAuthService
    {
        /// <summary>
        /// Registers a new user and returns the created ApplicationUser (email confirmation token is not returned here).
        /// </summary>
        Task<ApplicationUser> RegisterAsync(string email, string password, string? fullName = null, CancellationToken cancellationToken = default);

        /// <summary>
        /// Attempts to sign in and, on success, returns a JWT token string that contains role claims.
        /// Returns null on failure.
        /// </summary>
        Task<string?> LoginAsync(string email, string password, CancellationToken cancellationToken = default);

        /// <summary>
        /// Confirm email using token generated by Identity.
        /// </summary>
        Task<bool> ConfirmEmailAsync(string email, string token, CancellationToken cancellationToken = default);

        /// <summary>
        /// Generate a password reset token for a user (caller should send token to user via email).
        /// </summary>
        Task<string?> GeneratePasswordResetTokenAsync(string email, CancellationToken cancellationToken = default);

        /// <summary>
        /// Reset password using token.
        /// </summary>
        Task<bool> ResetPasswordAsync(string email, string token, string newPassword, CancellationToken cancellationToken = default);
    }
}